! Swedish menus for Varkon 2.0

m1  = "VARKON-EXPLICIT"
      "arkiv",m5
      "skapa",m11
      "redigera",m49
      "ta bort",m80
      "visa",m67
      "analys",m75
      "inställningar",m9
      "hjälp",m22;

m2  = "VARKON-GENERISK"
      "arkiv",m5
      "skapa",m11
      "ändra",m15
      "visa",m67
      "analys",m75
      "inställningar",m9
      "hjälp",m22;

m5  = "ARKIV"
      "öppna",m47
      "spara",f175
      "spara kopia som",m45
      "exportera",m24
      "macro",f152
      "kom till OS",f125
      "sluta",f123
      "spara/sluta",f122;

m9  = "INSTÄLLNINGAR"
      "kurv-noggr",f98
      "attribut",f16
      "modul",f127;

m10 = "TCOPY"
      "translation",f239
      "rotation",f240
      "spegling",f241
      "kopiering",f242;

m11 = "SKAPA"
      "punkt",m20
      "linje",m40
      "cirkelbåge",m55
      "kurvor",m60
      "ytor",m12
      "koordsystem",m25
      "text",m23
      "måttsättning",m50
      "tcopy",m10
      "grupp",f55
      "part",f25
      "importera",m39;

m12 = "YTOR"
      "bplan",f26
      "regel",f182
      "cylinder",f160
      "rotation",f158
      "svept",f181
      "offset",f159
      "approx",f235;

m15 = "ÄNDRA"
      "penna",f11
      "nivå",f12
      "linjebredd",f185
      "attribut",m16
      "storhet",M117
      "sats",f168
      "modul",f217
      "kompilera lib",f220
      "uppdatera part",f109
      "trimma",f6;

m16 = "ATTRIBUT"
      "linje",m17
      "cirkel",m17
      "kurva",m90
      "text",m18
      "mått",m19
      "snitt",m17;

m17 = "ATTRIBUT"
      "heldragen",f74
      "streckad",f76
      "centrum",f77
      "ny längd",f73;

m18 = "TEXT"
      "höjd",f78
      "bredd",f79
      "lutning",f89
      "typsnitt",f171
      "tpmode",f226;

m19 = "MÅTT"
      "sifferstorlek",f154
      "pilstorlek",f155
      "decimaler",f129
      "auto",f131
      "ej auto",f130;

m20 = "PUNKT"
      "fri",f19
      "projicerad",f21;

m22 = "HJÄLP"
      "om Varkon",M184
      "om hjälp",f150;

m23 = "TEXT"
      "vänster",f50
      "höger",M113
      "centrerad",M114
      "2 positioner",M115;
!      "font-editor",m93;

m24 = "EXPORTERA"
      "MBS",f144
      "DXF-2D",f92
      "DXF-3D",M398
      "STL",M1625
      "PLT",f151;

m25 = "KOORDSYSTEM"
      "pos/vinkel",f9
      "3 pos",f105;

m30 = "LÄNGDMÅTT"
      "horisontellt",f30
      "vertikalt",f31
      "parallellt",f32;

m33 = "DIAMETERMÅTT"
      "horisontellt",f33
      "vertikalt",f34
      "parallellt",f35;

m39 = "IMPORTERA"
      "DXF-2D",p388
      "DXF-3D",p389
      "IGES",p1624
      "STL",p1623
      "PLT",f145;

m40 = "LINJE"
      "två pos",f22
      "projicerad",f41
      "parallell",f23
      "pos/vinkel",f24
      "vinkelrät",f54
      "pos/tan",f28
      "tan/tan",f29;

m45 = "SPARA KOPIA SOM"
      "JOB-fil",f119
      "MBS-fil",f144
      "MBO-fil",f126
      "RES-fil",f121
      "alla filer",f201;

m47 = "ÖPPNA"
      "lagra först",f124
      "inget lagras",f120;

m49 = "REDIGERA"
      "ändra",m81
      "trimma",f6
      "dra",f202
      "flytta",f209
      "spegla",f211
      "rotera",f203
      "kopiera",f210;

m50 = "MÅTTSÄTTNING"
      "längdmått",m30
      "diametermått",m33
      "radiemått",f36
      "vinkelmått",f37
      "snitt",f38;

m55 = "CIRKELBÅGE"
      "1 pos/vinklar",f56
      "2 pos/radie",f57
      "3 pos",f58
      "offset",f59
      "hörnradie",f65;

m60 = "KURVOR"
      "spline",m89
      "kägelsnitt",m84
      "offset",f163
      "sammansatt",f75
      "trimmad",f232
      "isoparam",f230
      "skärning",f183
      "approx",f231;

m62 = "DOLDA KONT"
      "skärm",f133
      "fil",f134
      "båda",f135;

m63 = "FERGUSON"
      "med tang.",f70
      "utan tang.",f116;

m64 = "CHORD LENGTH"
      "med tang.",f71
      "utan tang.",f156;

m67 = "VISA"
      "färger",M1658
      "ljuskällor"M350
      "allt pekbart",f215
      "X11-fönster",f196
      "OpenGL-fönster",f200
      "dolda kont",m62;

m75 = "ANALYS"
      "formel",M393
      "geometri",m76 
      "part/grupp",m79
      "jobbstatus",M368
      "systemdata",m77;

m76 = "GEOMETRI"
      "en storhet",M356
      "position",M363
      "avstånd",M364
      "vinkel",M365
      "kurvor",m91
      "ytor",M1643
      "area",m86
      "tyngdpunkt",M417;

m77 = "SYSTEMDATA"
      "DB-data",f140
      "PM-data",f139;

m79 = "PART/GRUPP"
      "en part",M379
      "anropskedja",M418
      "referenser",f169
      "part medlemmar",M366
      "partlista",M378
      "strukturträd",p419
      "gm-lista",M420
      "grupp medlemmar",M360
      "grupplista",M361;

m80 = "TA BORT"
      "en storhet",f10
      "grupp",f13
      "släck",f213
      "tänd alla",f214;

m81 = "ÄNDRA"
      "penna",f11
      "nivå",f12
      "linjebredd",f185
      "attribut",m16
      "cirkel",m82
      "text",m83
      "grupp",f212
      "part",m35;

m82 = "CIRKEL"
      "radie",f204
      "startvinkel",f205
      "slutvinkel",f206;

m83 = "TEXT"
      "vinkel",f207
      "text",f208;

m84 = "KÄGELSNITT"
      "fri",f161
      "projicerad",f162;

m86 = "YTA"
      "2D-area",M416
      "kurva",M1591
      "yta",M1589;

m89 = "SPLINE"
      "ferguson",m63
      "chord length",m64
      "variable stiffness",m97;

m90 = "KURVATTRIBUT"
      "heldragen",f74
      "streckad",f76
      "centrum",f77
      "fylld",f218
      "ny längd",f73;

m91 = "KURVOR"
      "längd",M431
      "tangent",M432
      "normal",M434
      "bi-normal",M435
      "krökning",M433
      "inverser",m92;

m92 = "INVERSER"
      "position",M436
      "tangent",M437
      "krökning",M438
      "längd",M439;

m93 = "FONT_EDITOR"
      "mall",p176
      "punkter",f20
      "rita",M177
      "flytta",p178
      "generera fil",m94;

m94 = "GENERERA FIL"
       "detta tecken",M179
       "alla tecken",M180;

m97 = "VAR STIFFNESS"
      "med tang.",f72
      "utan tang.",f157;

m100 = "2 POSITIONER"
       "1 startpos",a1
       "2 slutpos",a2;

m101 = "PARALLELL"
       "linje",a1
       "avstånd",a2;

m102 = "POS-VINKEL"
       "startposition",a1
       "vinkel",a2
       "längd",a3;

m103 = "VINKELRÄT"
       "startposition",a1
       "linje",a2
       "längd",a3;

m104 = "POS-TANGENT"
       "startposition",a1
       "cirkel/kurva",a2
       "alternativ",a3;

m105 = "TAN-TAN"
       "1:a cirkel",a1
       "2:a cirkel",a2
       "alternativ",a3;

m106 = "1 POSITION"
       "origo",a1
       "radie",a2
       "startvinkel",a3
       "slutvinkel",a4;

m107 = "TVÅ POS"
       "1 startpos",a1
       "2 slutpos",a2
       "radie",a3;

m108 = "TRE POS"
       "1 startpos",a1
       "2 mittpos",a2
       "3 slutpos",a3;

m109 = "HÖRNRADIE"
       "1:a storhet",a1
       "2:a storhet",a2
       "radie",a3
       "alternativ",a4;

m110 = "OFFSET"
       "cirkel",a1
       "avstånd",a2;

m111 = "LÄNGDMÅTT"
       "1 startpos",a1
       "2 slutpos",a2
       "textpos",a3
       "alternativ",a4;

m112 = "DIAMETERMÅTT"
       "cirkel",a1
       "textpos",a2
       "alternativ",a3;

m113 = "RADIEMÅTT"
       "cirkel",a1
       "brytpos",a2
       "textpos",a3;

m114 = "VINKELMÅTT"
       "1:a linjen",a1
       "2:a linjen",a2
       "textpos",a3
       "alternativ",a4;

m115 = "TEXT"
       "position",a1
       "vinkel",a2
       "text",a3;

m116 = "SNITT"
       "avstånd",a1
       "vinkel",a2;

m117 = "KSYS 1P"
       "namn",a1
       "origo",a2
       "x-vinkel",a3
       "y-vinkel",a4
       "z-vinkel",a5;

m118 = "KSYS 3P"
       "namn",a1
       "origo",a2
       "x-axel",a3
       "y-axel",a4;

m119 = "B_PLAN"
       "1:a hörnet",a1
       "2:a hörnet",a2
       "3:e hörnet",a3
       "4:e hörnet",a4;

m120 = "KÄGELSNITT"
       "1 startpos",a1
       "2 starttang",a2
       "3 P-värde",a3
       "4 slutpos",a4
       "5 sluttang",a5;

m121 = "OFFSET"
       "kurva",a1
       "offset",a2;

m122 = "SPLINE"
       "1 startpos",a1
       "2 starttang",a2
       "3 slutpos",a3
       "4 sluttang",a4;

m123 = "SKÄRNING"
       "yta",a1
       "plan",a2;

m124 = "ISOPARAM"
       "surface",a1
       "type",a2
       "iso-value",a3
       "start",a4
       "end",a5;

m125 = "APPROX"
       "curve",a1
       "type",a2
       "method",a3
       "data" ,a4;

m126 = "TRIM"
       "curve",a1
       "start",a2
       "end" ,a3;

m127 = "SILHOUETTE"
       "surface",a1
       "direction",a2
       "type" ,a3
       "branch" ,a4;

m134= "GRUPP"
      "namn",a3
      "ta bort",a4
      "lägg till",a5;

m140= "POSITION"
      "absolut",a1
      "relativt",a2
      "hårkors",a3
      "ände",a4
      "på storhet",a5
      "centrum",a6
      "skärning",a7;

m141= "POSITION"
      "absolut",a1
      "relativt",a2
      "hårkors",a3
      "mbs",a4
      "ände",a5
      "på storhet",a6
      "centrum",a7
      "skärning",a8;

m143= "PARAMETERTYP"
      "heltal",a1
      "flyttal",a2
      "sträng",a3
      "vektor",a4;

m144= "MODULTYP"
      "geometri",a1
      "ritning",a2;

m145= "ATTRIBUT"
      "lokal",a1
      "global",a2
      "basic",a3;

m150= "OFFSET"
      "yta",a1
      "offset",a2;

m151= "ROTATION"
      "kurva",a1
      "startvinkel",a2
      "slutvinkel",a3
      "1:a position",a4
      "2:a position",a5;

m152= "CYLINDER"
      "kurva",a1
      "avstånd",a2
      "reversera",a3;

m153= "SVEPYTA"
      "profilkurva",a1
      "styrkurva",a2
      "reversera",a3;

m154 = "RULED"
       "1:st curve",a1
       "2:nd curve",a2
       "reverse",a3;

m155 = "TRIM"
       "surface",a1
       "u start",a2
       "u end"  ,a3
       "v start",a4
       "v end"  ,a5;

m156 = "IMPORT"
       "file name",a1
       "file type",a2
       "surface type",a3;

m157 = "SUR_CONIC"
       "1 start curve",a1
       "2 start tangent",a2
       "3 P-value",a3
       "4 end curve",a4
       "5 end tangent",a5;
