! Terminalfil för VT100 terminaler utan grafik.
!
! T-strängar
!
t350 = "ALFA"
t351 = "VT100"
!
! Snabbval
!
s1 = "%10",a1       ! vagnretur
s2 = "%8",a2        ! sudda
!s2 = "%127",a2      ! sudda, 127 på VAX
s3 = "%27[D",a4     ! markör-vänster
s4 = "%27[C",a5     ! markör-höger
s5 = "%27[A",a6     ! markör-uppåt
s6 = "%27[B",a7     ! markör-nedåt
s7 = "%9",a9        ! huvudmenyn
s8 = "%1",a10       ! hjälp
s9 = "%2",a11       ! pos-menyn
s10 = "%127",a12    ! Quit = <DEL>
s11 = "%3",a13      ! Interrupt = <CTL>c
!
