
! Terminalfil för X-windows.
!
! Specialtangenter
!
s1 = "%10",a1       ! vagnretur
s2 = "%8",a2        ! sudda
s3 = "%27[D",a4     ! mark|r-v{nster
s4 = "%27[C",a5     ! mark|r-h|ger
s5 = "%27[A",a6     ! mark|r-upp}t
s6 = "%27[B",a7     ! mark|r-ned}t
s7 = "%9",a9        ! huvudmenyn
s8 = "%1",a10       ! hjälp
s9 = "%2",a11       ! pos-menyn
s10 = "%127",a12    ! Quit = <DEL>
s11 = "%3",a13      ! Interrupt = <CTL>c
!
! Funktionstangenter
!
s21 = "%27A",f153  ! PF1  Help

