
! Terminalfil för X-windows.
!
! T-str{ngar
!
t350 = "X11"
t351 = "X11"
!
! Specialtangenter
!
s1 = "%10",a1       ! vagnretur
s2 = "%8",a2        ! sudda
s3 = "%27[D",a4     ! mark|r-v{nster
s4 = "%27[C",a5     ! mark|r-h|ger
s5 = "%27[A",a6     ! mark|r-upp}t
s6 = "%27[B",a7     ! mark|r-ned}t
s7 = "%9",a9        ! huvudmenyn
s8 = "%1",a10       ! hj{lp
s9 = "%2",a11       ! pos-menyn
s10 = "%127",a12    ! Quit = <DEL>
s11 = "%3",a13      ! Interrupt = <CTL>c
!
! Funktionstangenter
!
s21 = "%27A",m14  ! PF1  Byt aktivt attribut
s22 = "%27B",f96  ! PF2  Byt aktiv penna
s23 = "%27C",f90  ! PF3  Byt aktiv niv}
s24 = "%27D",f196 ! PF4  Nytt Fönster
s25 = "%27E",M356 ! PF5  Analysera en storhet
s26 = "%27F",M379 ! PF6  Analysera part
s27 = "%27G",M418 ! PF7  Anropskedja
s28 = "%27H",f146 ! PF8  Dekompilera
s29 = "%27I",f5   ! PF9  K|r aktiv modul
s30 = "%27J",f170 ! PF10 X-{ndra part
s31 = "%27K",f168 ! PF11 Editera
s32 = "%27L",f10  ! PF12 Ta bort storhet
!
! N}gra shiftade funktionstangenter, mest som test.
!
s33 = "%27a",f10  ! <SHIFT>PF1 Ta bort storhet
s34 = "%27b",f10  ! <SHIFT>PF2 Ta bort storhet
