##########################################################
#
#   Makefile for DBlib on Cray T3E
#
#  (C)Microform AB 1999-03-30 J.Kjellander
#
##########################################################

RM = rm -f

CC = cc

CFLAGS = -DUNIX

COMPILE = $(CC) -c $(CFLAGS)

include Makefile.DB

################################################################
