##########################################################
#
#   Makefile for EXlib on Cray T3E
#
#  (C)Microform AB 1999-03-30 J.Kjellander
#
##########################################################

RM = rm -f

CC = cc

CFLAGS = -O2 -DUNIX

COMPILE = $(CC) -c $(CFLAGS)

include Makefile.EX

##########################################################
