/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rap.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

RAPVAR_READ_NAME_RESP_TYPE *
rapvar_read_name_1(RAPVAR_READ_NAME_REQ_TYPE *argp, CLIENT *clnt)
{
	static RAPVAR_READ_NAME_RESP_TYPE clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, rapvar_read_name,
		(xdrproc_t) xdr_RAPVAR_READ_NAME_REQ_TYPE, (caddr_t) argp,
		(xdrproc_t) xdr_RAPVAR_READ_NAME_RESP_TYPE, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RAPVAR_WRITE_NAME_RESP_TYPE *
rapvar_write_name_1(RAPVAR_WRITE_NAME_REQ_TYPE *argp, CLIENT *clnt)
{
	static RAPVAR_WRITE_NAME_RESP_TYPE clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, rapvar_write_name,
		(xdrproc_t) xdr_RAPVAR_WRITE_NAME_REQ_TYPE, (caddr_t) argp,
		(xdrproc_t) xdr_RAPVAR_WRITE_NAME_RESP_TYPE, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RAPVAR_READ_NAME_ARRAY_RESP_TYPE *
rapvar_read_name_array_1(RAPVAR_READ_NAME_ARRAY_REQ_TYPE *argp, CLIENT *clnt)
{
	static RAPVAR_READ_NAME_ARRAY_RESP_TYPE clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, rapvar_read_name_array,
		(xdrproc_t) xdr_RAPVAR_READ_NAME_ARRAY_REQ_TYPE, (caddr_t) argp,
		(xdrproc_t) xdr_RAPVAR_READ_NAME_ARRAY_RESP_TYPE, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RAPVAR_WRITE_NAME_ARRAY_RESP_TYPE *
rapvar_write_name_array_1(RAPVAR_WRITE_NAME_ARRAY_REQ_TYPE *argp, CLIENT *clnt)
{
	static RAPVAR_WRITE_NAME_ARRAY_RESP_TYPE clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, rapvar_write_name_array,
		(xdrproc_t) xdr_RAPVAR_WRITE_NAME_ARRAY_REQ_TYPE, (caddr_t) argp,
		(xdrproc_t) xdr_RAPVAR_WRITE_NAME_ARRAY_RESP_TYPE, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
