##########################################################
#
#   Makefile for IGlib on FreeBSD
#
#  (C)2008-01-12 J.Kjellander
#
##########################################################

RM = rm -f

CC ?= gcc

CFLAGS +=   -ansi -ffloat-store -fsigned-char \
            -DUNIX -I/usr/local/include

debug :     CFLAGS += -g -DDEBUG

COMPILE = $(CC) -c $(CFLAGS)

include Makefile.IG

##########################################################
