##########################################################
#
#   Makefile for IGlib with gcc and FreeBSD
#
#  (C)Microform AB 1999-02-15 J.Kjellander
#
##########################################################

RM = rm -f

CC ?= gcc

CFLAGS +=   -ansi -ffloat-store -fsigned-char \
            -DUNIX -I/usr/X11R6/include

debug :     CFLAGS += -g -DDEBUG

COMPILE = $(CC) -c $(CFLAGS)

include Makefile.IG

##########################################################
