#!/bin/sh
#######################################################
#
# Startscript för Varkon
# Version: 2.0
# OS: Unix
# Language: Swedish
#
# Se kommentarerna nedan för instruktioner
# om hu systemet kan configureras.
#
# URL:  http://varkon.sourceforge.net
# (C)2007 J.Kjellander
#
#######################################################

# VARKON_ROOT är systemets huvudkatalog. Om resten
# av systemet är installerat under denna på normalt
# vis räcker det att ändra VARKON_ROOT för att kunna
# starta. Övriga environmentparametrar är kopplade till
# VARKON_ROOT men kan förstås ändras om så önskas.
# Alternativ 1, hitta relativ sökväg härifrån.
# Alternativ 2, ange sökägen explicit.
VARKON_ROOT=`(cd $(dirname $0); cd ..; cd ..; pwd)`
# VARKON_ROOT=/home/username/varkon/varkon_2.Xx
export VARKON_ROOT

# Svenska menyfiler.
VARKON_MDF=$VARKON_ROOT/mdf/swedish/x11.MDF
export VARKON_MDF

# Felmeddelandefiler
VARKON_ERM=$VARKON_ROOT/erm
export VARKON_ERM

# Manualen
VARKON_DOC=$VARKON_ROOT/man
export VARKON_DOC

# Moduler (MBO-filer)
VARKON_LIB=$VARKON_ROOT/lib
export VARKON_LIB

# Temporäfiler. Här kan man istället välja tex. bara /tmp
# om den finns. I ett nätverk kan man spara lite prestanda
# om temporärfiler får ligga på den lokala maskinen.
# Alla användare måste ha både skriv- och läs-rättigheter
# till denna katalog.
VARKON_TMP=$VARKON_ROOT/tmp
export VARKON_TMP

# Fontfiler för grafisk text.
VARKON_FNT=$VARKON_ROOT/cnf/fnt
export VARKON_FNT

# Filer för konfiguration av plottrar. Dessa brukar man
# istället lägga på tex. $HOME/cnf/plt så att ev. ändringar
# kvarstår när en ny version av VARKON installeras.
# Alla användare måste ha både skriv- och läs-rättigheter
# till denna katalog.
VARKON_PLT=$VARKON_ROOT/cnf/plt
export VARKON_PLT

# Eventuella ikonfiler (bitmappar)
VARKON_ICO=$VARKON_ROOT/cnf/icons
export VARKON_ICO

# Filer med toleranser
VARKON_TOL=$VARKON_ROOT/cnf/tol
export VARKON_TOL

# X-Windows resurser på svenska
VARKON_INI=$VARKON_ROOT/cnf/ini/swedish
export VARKON_INI

# Exekverbara binärer (xvarkon, mbsc, plotprogram)
VARKON_BIN=$VARKON_ROOT/bin
export VARKON_BIN

# Path till shared ODBC library. Avkommentera följande två
# rader och sätt sökvägen att peka på det ställe där du
# har ODBC-biblioteken installerade om du har byggt ihop
# Varkon med stöd för ODBC.

#LD_LIBRARY_PATH=/usr/lib/unixODBC
#export LD_LIBRARY_PATH

# Starta VARKON. Använd GLOBAL som default för nya jobb.
$VARKON_BIN/xvarkon -GLOBAL -i$VARKON_INI/linux

# Om man vill kan man även lägga till en egen ini-fil
# med X-resurser som då laddas efter VARKON:s ordinarie
# fil. Tex. nått i stil med:

# $VARKON_BIN/xvarkon -GLOBAL \
# -i$VARKON_INI/linux -i$HOME/cnf/ini/swedish/min_egen_inifil

# Ladda alltid den ordinarie filen först och lägg alla egna ändringar
# i den egna filen. Det är det sist laddade som gäller. Ändra inte
# i standardfilen.

# Vill man köra systemet i ritnings-mode lägger man till "-EXPLICIT" på
# kommandoraden.
# $VARKON_BIN/xvarkon -EXPLICIT $1 $2 -i$VARKON_INI/linux
#
# Vill man specificera ett default jobbibliotek kan man göra
# på följande vis:
# $VARKON_BIN/xvarkon -GLOBAL -jd/home/min_katalog/mina_varkonjobb