<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
<head>
  <title> _TITLE_ _SUBTITLE_ </title>
  <link rel="stylesheet" href=_STYLE_>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>
<body>
<a name="top"/>

<p style="float:right; margin-bottom:0; font-size:0.8em">_INDEXLINK_</p>

<p style="margin-bottom:0; font-size:0.8em">_TITLE_</p>

<hr style="margin-top:2px; margin-bottom:4em"/>