##########################################################
#
#   Makefile for PMlöib on Cray T3E
#
#  (C)Microform AB 1999-03-30 J.Kjellander
#
##########################################################

RM = rm -f

CC = cc

CFLAGS = -O2 -DUNIX -DV3_X11 -DWRK_STAT

COMPILE = $(CC) -c $(CFLAGS)

include Makefile.PM

################################################################
