
! Terminal file for X-windows

t350 = "X11"
t351 = "X11"

! Special keys

s1 = "%10",a1       ! Return
s2 = "%8",a2        ! Erase
s3 = "%27[D",a4     ! Cursor left
s4 = "%27[C",a5     ! Cursor right
s5 = "%27[A",a6     ! Cursor up
s6 = "%27[B",a7     ! Cursor down
s7 = "%9",a9        ! Main menu
s8 = "%1",a10       ! Help
s9 = "%2",a11       ! pos-menu
s10 = "%127",a12    ! Quit = <DEL>
s11 = "%3",a13      ! Interrupt = <CTL>c

! Function keys

s21 = "%27A",m14  ! PF1  Change active attribute
s22 = "%27B",f96  ! PF2  Change active pen
s23 = "%27C",f90  ! PF3  Change active level
s24 = "%27D",f196 ! PF4  New window
s25 = "%27E",M356 ! PF5  Analyse entity
s26 = "%27F",M379 ! PF6  Analyse part
s27 = "%27G",M418 ! PF7  Callchain
s28 = "%27H",f146 ! PF8  Decompile
s29 = "%27I",f5   ! PF9  Run active module
s30 = "%27J",f170 ! PF10 PChange
s31 = "%27K",f168 ! PF11 Edit
s32 = "%27L",f10  ! PF12 Delete
