! Terminal file for X-windows

! Special keys

s1 = "%10",a1       ! Return
s2 = "%8",a2        ! Erase
s3 = "%27[D",a4     ! Cursor left
s4 = "%27[C",a5     ! Cursor right
s5 = "%27[A",a6     ! Cursor up
s6 = "%27[B",a7     ! Cursor down
s7 = "%9",a9        ! Main menu
s8 = "%1",a10       ! Help
s9 = "%2",a11       ! pos-menu
s10 = "%127",a12    ! Quit = <DEL>
s11 = "%3",a13      ! Interrupt = <CTL>c

! Function keys

s21 = "%27A",f153 ! PF1  Help

