##########################################################
#
#   Makefile for PL on Cray T3E
#
#  (C)Microform AB 1999-03-31 J.Kjellander
#
##########################################################

RM = rm -f

CC = cc

CFLAGS = -DUNIX -DWRK_STAT

COMPILE = $(CC) $(CFLAGS)

include Makefile.PL

##########################################################
