##########################################################
#
#   Makefile for PL on HP workstations
#
#  (C)Microform AB 1999-11-04 J.Kjellander
#
##########################################################

RM = rm -f

CC = cc

CFLAGS =                    \
         -O                 \
         -DUNIX             \
         -DWRK_STAT

COMPILE = $(CC) $(CFLAGS)

include Makefile.PL

##########################################################
